require("settings")
require("keymaps")
require("autocommands")
require("theme")
require("colors")
require("plugins")
-- require("plugins.nvim-tree")
-- require("plugins.treesitter")
-- require("plugins.bufferline")
-- require("plugins.other")
-- require("plugins.lsp")
-- require("plugins.lualine")
-- require("plugins.cmp")
-- require("plugins.autopairs")
-- require("plugins.lualine")
-- require("plugins.toggleterm")
-- require("plugins.dashboard")
require("plugins.comment")
require("plugins.twilight")
require("plugins.zen-mode")
