require("core.settings")
-- require("core.keymaps")
require("core.mappings")
-- require("core.autocmd")
require("core.autocommand")
require("core.theme")
-- require("custom.highlights")
require("custom.abbrev")
require("custom.overrides")
require("custom.statusline")
require("plugins")
