require("core.settings")
require("core.mappings")
require("core.autocommand")
require("core.theme")
require("custom.abbrev")
require("custom.overrides")
require("custom.statusline")
require("plugins.plugins")
