local M = {}

M.settings = {
  impatient = true,
  plenary = true,
  icons = true,
  themer = false,
  base16 = true,
  bufferline = true,
  neorg = true,
  explorer = true,
  treesitter = true,
  treesitter_txtobj = true,
  rainbow_paren = true,
  autotag = false,
  autopairs = true,
  playground = true,
  lsp = true,
  installer = true,
  null = true,
  cmp = true,
  cmp_luasnip = true,
  cmp_nvim_lsp = true,
  cmp_buffer = true,
  cmp_path = true,
  cmp_npm = false,
  luasnip = true,
  friendly_snip = true,
  telescope = true,
  telescope_fzf = true,
  colorizer = false,
  indent = true,
  comment = true,
  terminal = false,
  harpoon = true,
  zenmode = false,
  trouble = true,
  neogen = true,
  git = true,
  paperplanes = false,
  lightspeed = true,
  scratch = false,
}

return M
